import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import { auth } from "../../auth";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Providers from "./components/Providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currUserSession = await auth()

  //TODO:set the refresh token
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider
         session={currUserSession}
         refetchInterval={20}
         basePath="/"
        // refetchOnWindowFocus={true}
         >
          <Providers>
            <div className="flex w-screen overflow-x-hidden flex-col h-screen">
              <Navbar />
              {children}
              <Footer />
            </div>
          </Providers>
        </SessionProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
