import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Providers from "./components/Providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <Providers>
        <div className="flex w-screen overflow-x-hidden flex-col h-screen">
           <Navbar />
        {children}
        <Footer/>
        </div></Providers>
       <Toaster position="top-right" richColors/>
      </body>
    </html>
  );
}
