{
  "videoDetails": {
      "embed": {
          "iframeUrl": "https://www.youtube.com/embed/0wz6RfUXT0w",
          "width": 1280,
          "height": 720
      },
      "title": "20 Second Timer Bomb [3D TIMER] 💣",
      "description": "What's better than a timer bomb 💣? How about a timer bomb in 3D? Watch the fuse burn all the way down to the bomb and then...it's a MASSIVE EXPLOSION 💥 in your face. Hold on to your butt. \n📌WATCH NEXT:  Overcharging Phone Battery !!10000000%⚡ https://youtu.be/NTk9YBEmbyw\n\n Journey to 1 MILLION 📈\n ⭐️||||||||||||||. 45% ............... 456K/1M ⭐️\n🚨 SUBSCRIBE https://bit.ly/30COX6E\n\n👉 DONATE\nhttps://bit.ly/3pkGmo7\n \n💬 JOIN US IN THE COMMENTS\nWE LIKE TO HAVE FUN!\n\n#timertopia",
      "lengthSeconds": "26",
      "ownerProfileUrl": "http://www.youtube.com/@TimerTopia",
      "externalChannelId": "UCNzaFfNN0kMy8WmbE6lIw8g",
      "isFamilySafe": true,
      "availableCountries": [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AU",
          "AW",
          "AX",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BL",
          "BM",
          "BN",
          "BO",
          "BQ",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CU",
          "CV",
          "CW",
          "CX",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GG",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IM",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JE",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MF",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PK",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "SS",
          "ST",
          "SV",
          "SX",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "US",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW"
      ],
      "isUnlisted": false,
      "hasYpcMetadata": false,
      "viewCount": "4603469",
      "category": "Education",
      "publishDate": "2022-06-13T07:00:02-07:00",
      "ownerChannelName": "Timer Topia",
      "uploadDate": "2022-06-13T07:00:02-07:00",
      "videoId": "0wz6RfUXT0w",
      "keywords": [
          "20 second timer bomb",
          "20 second timer bomb loud",
          "20 second timer",
          "20 second timer with sound",
          "timer topia",
          "timer bomb",
          "bomb timer",
          "20 second bomb timer",
          "20 second bomb"
      ],
      "channelId": "UCNzaFfNN0kMy8WmbE6lIw8g",
      "isOwnerViewing": false,
      "isCrawlable": true,
      "allowRatings": true,
      "author": {
          "id": "UCNzaFfNN0kMy8WmbE6lIw8g",
          "name": "Timer Topia",
          "user": "@TimerTopia",
          "channel_url": "https://www.youtube.com/channel/UCNzaFfNN0kMy8WmbE6lIw8g",
          "external_channel_url": "https://www.youtube.com/channel/UCNzaFfNN0kMy8WmbE6lIw8g",
          "user_url": "http://www.youtube.com/@TimerTopia",
          "thumbnails": [
              {
                  "url": "https://yt3.ggpht.com/Nkp_BHNMhReBeETEosqa1OGokmG7Wo_Gf3EnFJms7Ielxg2KzDicydU9v3xPNwHkPNxJ9VEo3w=s48-c-k-c0x00ffffff-no-rj",
                  "width": 48,
                  "height": 48
              },
              {
                  "url": "https://yt3.ggpht.com/Nkp_BHNMhReBeETEosqa1OGokmG7Wo_Gf3EnFJms7Ielxg2KzDicydU9v3xPNwHkPNxJ9VEo3w=s88-c-k-c0x00ffffff-no-rj",
                  "width": 88,
                  "height": 88
              },
              {
                  "url": "https://yt3.ggpht.com/Nkp_BHNMhReBeETEosqa1OGokmG7Wo_Gf3EnFJms7Ielxg2KzDicydU9v3xPNwHkPNxJ9VEo3w=s176-c-k-c0x00ffffff-no-rj",
                  "width": 176,
                  "height": 176
              }
          ],
          "verified": true,
          "subscriber_count": 456000
      },
      "isPrivate": false,
      "isUnpluggedCorpus": false,
      "isLiveContent": false,
      "media": {},
      "likes": null,
      "dislikes": null,
      "age_restricted": false,
      "video_url": "https://www.youtube.com/watch?v=0wz6RfUXT0w",
      "storyboards": [
          {
              "templateUrl": "https://i.ytimg.com/sb/0wz6RfUXT0w/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjukomVBg%3D%3D&sigh=rs%24AOn4CLAbppBrz9JxRtl7TYYbIelLypVjZg",
              "thumbnailWidth": 48,
              "thumbnailHeight": 27,
              "thumbnailCount": 100,
              "interval": 0,
              "columns": 10,
              "rows": 10,
              "storyboardCount": 1
          },
          {
              "templateUrl": "https://i.ytimg.com/sb/0wz6RfUXT0w/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjukomVBg%3D%3D&sigh=rs%24AOn4CLASHFtSTTRU-gPuCJcj9iCd53QatA",
              "thumbnailWidth": 80,
              "thumbnailHeight": 45,
              "thumbnailCount": 27,
              "interval": 1000,
              "columns": 10,
              "rows": 10,
              "storyboardCount": 1
          },
          {
              "templateUrl": "https://i.ytimg.com/sb/0wz6RfUXT0w/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjukomVBg%3D%3D&sigh=rs%24AOn4CLBv1TnHbGXiDJK6v_-KhRUE0_YxZg",
              "thumbnailWidth": 160,
              "thumbnailHeight": 90,
              "thumbnailCount": 27,
              "interval": 1000,
              "columns": 5,
              "rows": 5,
              "storyboardCount": 2
          }
      ],
      "chapters": [],
      "thumbnails": [
          {
              "url": "https://i.ytimg.com/vi/0wz6RfUXT0w/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDLte4s_x6fzPp_MX7dJWUMizBm5Q",
              "width": 168,
              "height": 94
          },
          {
              "url": "https://i.ytimg.com/vi/0wz6RfUXT0w/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAHaR_v8flzHwPpKeuEdDDydnWIYQ",
              "width": 196,
              "height": 110
          },
          {
              "url": "https://i.ytimg.com/vi/0wz6RfUXT0w/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBSBxzbdG2uMur4j9eAN3dkuGSUUQ",
              "width": 246,
              "height": 138
          },
          {
              "url": "https://i.ytimg.com/vi/0wz6RfUXT0w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVEJlwEtXeNhB5DzDzrUF3ZeWyGw",
              "width": 336,
              "height": 188
          },
          {
              "url": "https://i.ytimg.com/vi/0wz6RfUXT0w/maxresdefault.jpg",
              "width": 1920,
              "height": 1080
          }
      ]
  }
}